import 'package:flutter/material.dart';
import '../../widgets/word_definition_sheet.dart';
import '../../widgets/exercise_settings_sheet.dart';

/// Sınavlarda çıkma ihtimali yüksek kelimelerin serbest gözatma listesi.
/// Süre baskısı yok — öğrenci istediği zaman açıp göz gezdirebilir,
/// dokununca TDK'dan anlamını görebilir.
class ExamWordsPage extends StatefulWidget {
  const ExamWordsPage({super.key});

  @override
  State<ExamWordsPage> createState() => _ExamWordsPageState();
}

class _ExamWordsPageState extends State<ExamWordsPage> {
  Color _color = const Color(0xFFB45309);

  static const List<Color> _colorPalette = [
    Color(0xFFB45309),
    Color(0xFFEC4899),
    Color(0xFFEA580C),
    Color(0xFF0D9488),
    Color(0xFF7C3AED),
    Color(0xFF2563EB),
  ];

  static const List<String> _page1 = [
    'Anlam',
    'Kavram',
    'Hikaye',
    'Şiir',
    'Efsane',
    'Deyim',
    'Betimleme',
    'Tema',
    'Konu',
    'Fiil',
    'Çarpma',
    'Oran',
    'Olay',
    'Biyografi',
    'Doğru',
    'Bölme',
    'Çember',
    'Kesir',
    'Paralel',
    'Hacim',
    'Molekül',
    'Üçgen',
    'Kare',
    'Atom',
    'Karışım',
    'Enerji',
    'Kuvvet',
    'Çözünürlük',
    'Elektrik',
    'Devre',
    'Çekim',
    'İskelet',
    'Kalıtım',
    'Haber',
    'Solunum',
    'Denge',
    'Kültür',
    'Devlet',
    'Anayasa',
    'İklim',
    'Barış',
    'Kimyasal',
    'Savaş',
    'Tarım',
    'Kıta',
    'Deniz',
    'Kuzey',
    'Şehir',
    'Cumhuriyet',
    'Yaklaşım',
    'Mera',
    'Akarsu',
    'Nehir',
    'Kasaba',
    'Tarih',
    'Coğrafya',
    'Temsilci',
    'Kapsam',
    'Üslup',
    'Eleştiri',
    'Tezat',
    'Abartı',
    'Yarımada',
    'Özgün',
    'Termal',
    'Bağlam',
    'İfade',
    'Anlatım',
    'Duygu',
    'Yakınçağ',
    'Derinlik',
    'Gözlem',
    'İzlenim',
    'Tartışma',
    'İletişim',
    'Söylem',
    'Bağımsızlık',
    'Özdeyiş',
    'Boylam',
    'Önyargı',
    'Mantık',
    'Sonuç',
    'Çelişki',
    'Vatandaşlık',
    'Süreç',
    'Aşama',
    'Delta',
    'Sezgi',
    'Miras',
    'Nitelik',
    'Kurgulamak',
    'Nicelik',
    'Belirgin',
    'Direnç',
    'Harita',
    'Reklam',
    'Sosyal',
    'Farkındalık',
    'Tarım',
    'Sulama',
    'Toprak',
    'Sağlık',
    'Egzersiz',
    'Sonuç',
    'Karşılaştırma',
    'Medya',
    'Gelişme',
    'Deney',
    'Hipotez',
    'Meclis',
    'Kütle',
    'Sorgulamak',
    'Spor',
    'Müzik',
    'Trafik',
    'Protein',
    'Kırsal',
    'Mineral',
    'Vurgulamak',
    'Giriş',
    'Tekil',
    'Soyut',
    'Eklem',
    'Tiyatro',
    'Somut',
    'Karakter',
    'İlim',
    'Sinir',
    'Sinema',
    'Damar',
    'Hasat',
    'Atasözü',
    'Sürükleyici',
    'Sanat',
    'Tekrar',
    'Tümleç',
    'Zarf',
    'Cümle',
    'Kültür',
    'Fotosentez',
    'Heyelan',
    'Zamir',
    'Görenek',
    'Krater',
    'Levha',
    'Bütçe',
    'Adaptasyon',
    'Vitamin',
    'Çoğul',
    'Sıfat',
    'Uydu',
    'Galaksi',
    'Gelenek',
    'Medeniyet',
    'Özne',
    'Yıldız',
    'Yankı',
    'Frekans',
    'Yansıma',
    'Yüklem',
    'Okyanus',
  ];

  static const List<String> _page2 = [
    'Bakteri',
    'Hijyen',
    'Güzel',
    'Zanaat',
    'Cenk',
    'Zafer',
    'Ekosistem',
    'Samimi',
    'Tatlı',
    'Zeybek',
    'Hünkâr',
    'Türkmen',
    'Kalpak',
    'Sindirim',
    'Dingin',
    'Hançer',
    'Kardeş',
    'Meslek',
    'Kervan',
    'Güven',
    'Metabolizma',
    'Umut',
    'Ahilik',
    'Sancak',
    'Şefkat',
    'Değer',
    'Bağlılık',
    'Bağışıklık',
    'Ferah',
    'Yemin',
    'Tüccar',
    'Töre',
    'Umut',
    'Aşiret',
    'Hastalık',
    'Sevgi',
    'Kaftan',
    'Neşe',
    'Yiğit',
    'Korkut',
    'Ödev',
    'Mikroskop',
    'Destan',
    'Umut',
    'Sevgi',
    'Barış',
    'Huzur',
    'Sıcaklık',
    'Element',
    'Dostluk',
    'Proje',
    'Saat',
    'Konu',
    'Çizim',
    'Test',
    'Malazgirt',
    'Sınav',
    'Harita',
    'Fırça',
    'Desen',
    'Nota',
    'Melodi',
    'Mutluluk',
    'Takvim',
    'Çeviri',
    'Odak',
    'Uzantı',
    'Ulusal',
    'Varsayım',
    'Organizma',
    'Tuval',
    'Öngörü',
    'Gelgit',
    'Yükümlü',
    'Özenti',
    'Yavan',
    'Gülümse',
    'Nezaket',
    'Metot',
    'Kalıcı',
    'Özdeş',
    'Maksat',
    'Yargı',
    'Sağduyu',
    'Yapıtaşı',
    'Kuşku',
    'İmge',
    'Dipnot',
    'İrade',
    'Lirik',
    'Alternatif',
    'Yapaylık',
    'Drama',
    'Boyut',
    'Deneyim',
    'Coşkun',
    'Kaynak',
    'Perspektif',
    'Yenilik',
    'Kanaat',
    'Mahlas',
    'Ayrıntı',
    'Kaygı',
    'Anlatım',
    'Kompozisyon',
    'Yinele',
    'Kalıp',
    'Özlü',
    'Sanal',
    'Kitle',
    'Klişe',
    'Enstrüman',
    'Trajedi',
    'Rastgele',
    'Çalışma',
    'Simge',
    'Sentez',
    'Biçim',
    'Jimnastik',
    'Otorite',
    'Sulh',
    'Taslak',
    'Analiz',
    'Yalın',
    'Kalıcı',
    'Antrenman',
    'Özveri',
    'Garp',
    'İrdele',
    'İrade',
    'Ocak',
    'Özerk',
    'Peygamber',
    'Koşul',
    'Çehre',
    'Hüzün',
    'Alaca',
    'Sığ',
    'Hicret',
    'Üstünkörü',
    'Katmerli',
    'İvedi',
    'Hoşgörü',
    'Çelişki',
    'Bulgu',
    'İleti',
    'Terennüm',
    'İzlenim',
    'Örtük',
    'Seçkin',
    'Çevik',
    'İkilem',
    'Refleks',
    'Tökezlemek',
    'İrkilmek',
    'Faktör',
    'Arşiv',
    'Karşıt',
    'Motif',
    'Özlem',
    'Örselenmek',
  ];

  Widget _wordRow(BuildContext context, String word, {required bool isLast}) {
    return InkWell(
      onTap: () => showWordDefinition(context, word, accentColor: _color),
      child: Column(
        children: [
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
            child: Row(
              children: [
                Icon(
                  Icons.menu_book_outlined,
                  size: 16,
                  color: _color.withValues(alpha: 0.6),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    word,
                    style: const TextStyle(
                      fontSize: 15,
                      fontWeight: FontWeight.w600,
                      color: Color(0xFF0F172A),
                    ),
                  ),
                ),
                Icon(
                  Icons.touch_app_outlined,
                  size: 15,
                  color: Colors.grey.shade400,
                ),
              ],
            ),
          ),
          if (!isLast) Divider(height: 1, color: Colors.grey.shade200),
        ],
      ),
    );
  }

  Widget _pageSection(BuildContext context, String title, List<String> words) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          '$title  ·  ${words.length} kelime',
          style: TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 15,
            color: _color,
          ),
        ),
        const SizedBox(height: 10),
        Container(
          width: double.infinity,
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(16),
            border: Border.all(color: Colors.grey.shade200),
          ),
          child: Column(
            children: [
              for (int i = 0; i < words.length; i++)
                _wordRow(context, words[i], isLast: i == words.length - 1),
            ],
          ),
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          'Sınav Kelimeleri',
          style: TextStyle(fontWeight: FontWeight.bold),
        ),
        centerTitle: true,
        actions: [
          IconButton(
            onPressed: () => showExerciseSettingsSheet(
              context,
              currentColor: _color,
              colorOptions: _colorPalette,
              onColorChanged: (c) => setState(() => _color = c),
            ),
            icon: const Icon(Icons.more_vert_rounded),
            tooltip: 'Ayarlar',
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
              decoration: BoxDecoration(
                color: Colors.amber.shade50,
                borderRadius: BorderRadius.circular(14),
                border: Border.all(color: Colors.amber.shade200),
              ),
              child: Row(
                children: [
                  const Text('⚠️', style: TextStyle(fontSize: 20)),
                  const SizedBox(width: 10),
                  Expanded(
                    child: Text(
                      'Bu kelimeler sınavda kesin çıkar! Anlamını bilmediğin '
                      'bir kelimeye dokun, TDK sözlüğünden anlamını gör.',
                      style: TextStyle(
                        fontSize: 13,
                        fontWeight: FontWeight.w600,
                        color: Colors.amber.shade900,
                      ),
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 20),
            _pageSection(context, '1. Sayfa', _page1),
            const SizedBox(height: 24),
            _pageSection(context, '2. Sayfa', _page2),
            const SizedBox(height: 12),
          ],
        ),
      ),
    );
  }
}
